const prompts = [
    "wizard's staff",
    "waterfall",
    "zombies",
    "sandcastle",
    "fangs",
    "tattoo",
    "family crest",
    "spaceship",
    "mythical beast",
    "spooky tree",
    "alien",
    "tropical cocktail",
    "robot",
    "dragons",
    "tombstone",
    "medieval goblet",
    "king's throne",
    "mermaid",
    "vampire",
    "witch's cauldron",
    "tooth fairy",
    "deep sea monster",
    "magic carpet",
    "sculpture",
    "coral reef",
    "wine bottle",
    "statue of liberty",
    "beauty",
    "beast",
    "elephant",
    "mayan ruins",
    "birds",
    "camera",
    "bowl of soup",
    "breakfast",
    "snack",
    "lunch",
    "dinner",
    "flower base",
    "ladder",
    "full moon",
    "bright sun",
    "autumn",
    "spring",
    "summer",
    "winter",
    "butterfly",
    "caterpillar",
    "troll",
    "roller skates",
    "rain boots",
    "weeds",
    "flowers",
    "bedroom",
    "kitchen",
    "dining room",
    "bathroom",
    "egg hatching",
    "wrist watch",
    "night",
    "harvest",
    "pond",
    "raincoat",
    "hat",
    "water bottle",
    "flashlight",
    "top hat",
    "sailboat",
    "dandelion",
    "earthworm",
    "bank robber",
    "policeman",
    "superhero",
    "villain",
    "a view out a window",
    "cactus",
    "sunflowers",
    "mosquito",
    "spider web",
    "star fish",
    "flip flops",
    "lawn chair",
    "trampoline",
    "pots and pans",
    "sword",
    "lighthouse",
    "pie on a windowsill",
    "houseplant",
    "soldier",
    "chimney",
    "barbed wire",
    "squirrel",
    "hot sauce",
    "chain",
    "beehive",
    "helicopter",
    "hot dog",
    "venus flytrap",
    "stained glass",
    "sphinx",
    "skateboard",
    "serenity",
    "open book",
    "werewolf",
    "hourglass",
    "tower",
    "camel",
    "cleopatra",
    "Your favorite book character",
    "Desert",
    "Forest",
    "Mountains",
    "Ocean",
    "Pumpkin seed",
    "Pinecone",
    "Octopus",
    "Mannequin",
    "Lollipop",
    "Sticky",
    "Footprints",
    "Tractor",
    "Slime",
    "Island paradise",
    "Sand dune",
    "Archer",
    "Your favorite outfit",
    "Trophies",
    "Fishing fly",
    "Blackhole",
    "Cyclops",
    "Swan",
    "Mirror",
    "Microphone",
    "Pretzels",
    "Newspaper",
    "Submarine",
    "Scrambled eggs",
    "Eel",
    "Wave",
    "Bike",
    "Leather boots",
    "Keys",
    "Coffee cup",
    "Self-portrait",
    "Snake charmer",
    "Playground",
    "Sumo wrestler",
    "Chrystal chandelier",
    "Eight ball",
    "Secrets",
    "Treasure chest",
    "Children's toy",
    "Something sparkly",
    "Penguin",
    "Unicorn",
    "Pirate",
    "Tribal pattern",
    "Suit of armor",
    "Pinball machine",
    "Erupting volcano",
    "Seahorse",
    "Ninja",
    "Happy monster",
    "Futuristic car",
    "Three little pigs",
    "Magic amulet",
    "Yeti",
    "Toolbox",
    "Fish bones",
    "Zipper",
    "Carpenter",
    "Handcuffs",
    "Dollhouse",
    "Mask",
    "Telescope",
    "Piano",
]

export default prompts